In [1]:
from glob import glob
import pandas as pd

In [2]:
files = glob('dataset/*.csv')
files

['dataset/gdp_Odisha1.csv',
 'dataset/gdp_Haryana.csv',
 'dataset/gdp_Punjab1.csv',
 'dataset/gdp_Kerala1.csv',
 'dataset/gdp_Maharashtra2.csv',
 'dataset/gdp_AndhraPradesh1.csv',
 'dataset/gdp_Bihar2.csv',
 'dataset/gdp_WestBengal2.csv',
 'dataset/gdp_Assam1.csv',
 'dataset/gdp_Bihar1.csv',
 'dataset/gdp_Karnataka2.csv',
 'dataset/elementary_2015_16.csv',
 'dataset/gdp_MadhyaPradesh.csv',
 'dataset/gdp_Uttarakhand.csv',
 'dataset/gdp_Tamilnadu.csv',
 'dataset/gdp_Jharkhand.csv',
 'dataset/gdp_Assam2.csv',
 'dataset/gdp_AndhraPradesh2.csv',
 'dataset/gdp_Maharashtra1.csv',
 'dataset/gdp_Meghalaya.csv',
 'dataset/gdp_UttarPradesh1.csv',
 'dataset/gdp_Punjab2.csv',
 'dataset/gdp_Kerala2.csv',
 'dataset/gdp_HimachalPradesh.csv',
 'dataset/gdp_Sikkim.csv',
 'dataset/gdp_Chattisgarh.csv',
 'dataset/gdp_Rajasthan1.csv',
 'dataset/gdp_Rajasthan2.csv',
 'dataset/gdp_UttarPradesh2.csv',
 'dataset/gdp_Odisha2.csv',
 'dataset/gdp_Karnataka1.csv',
 'dataset/gdp_Manipur.csv',
 'dataset/india-districts-census-2011.csv',
 'dataset/india_census_housing-hlpca-full.csv',
 'dataset/gdp_ArunachalPradesh.csv',
 'dataset/gdp_WestBengal1.csv',
 'dataset/gdp_Mizoram.csv']

In [3]:
len(files)

37

In [4]:
dfs = [pd.read_csv(file) for file in files]

In [5]:
dfs[0]

,Year,Description,Angul,Balangir,Balasore,Bargarh,Baudh,Bhadrak,Cuttack,Deogarh,...,Malkangiri,Mayurbhanj,Nabarangpur,Nayargarh,Nuapada,Puri,Rayagada,Sambalpur,Sonapur,Sundargarh
0,1999-00,GDP (in Rs. Cr.),3360.520000,1416.820000,1814.500000,1489.300000,363.140000,976.020000,2962.050000,352.010000,...,532.640000,2003.640000,916.450000,666.710000,559.620000,1435.630000,940.570000,1505.600000,494.200000,3123.190000
1,2000-01,GDP (in Rs. Cr.),3314.310000,1263.150000,1938.160000,1265.100000,342.240000,973.610000,3018.440000,322.290000,...,485.030000,2007.550000,867.940000,672.220000,543.310000,1434.970000,952.470000,1389.540000,480.270000,2918.740000
2,2001-02,GDP (in Rs. Cr.),2997.570000,1441.840000,2019.010000,1444.240000,387.710000,1124.040000,3238.920000,364.800000,...,513.110000,2142.580000,894.070000,748.460000,613.760000,1551.450000,991.900000,1491.240000,532.940000,2554.610000
3,2002-03,GDP (in Rs. Cr.),3515.410000,1348.020000,1928.330000,1269.890000,385.720000,1097.060000,3327.350000,298.410000,...,480.740000,2001.750000,861.960000,718.720000,529.960000,1590.550000,1001.150000,1417.900000,459.340000,2948.410000
4,2003-04,GDP (in Rs. Cr.),4181.100000,1622.460000,2231.140000,1510.950000,449.370000,1271.580000,3631.500000,343.430000,...,527.040000,2317.990000,956.390000,835.740000,602.320000,1806.420000,1151.870000,1606.640000,511.790000,3344.250000
5,2004-05,GDP (in Rs. Cr.),5155.140000,1759.490000,2550.150000,1548.810000,467.330000,1435.190000,4156.240000,349.530000,...,557.330000,2512.770000,1026.310000,847.360000,608.730000,1974.110000,1337.580000,1788.490000,574.890000,3836.390000
6,2005-06,GDP (in Rs. Cr.),4463.820000,1863.680000,2710.640000,1730.280000,494.300000,1550.670000,4482.730000,387.120000,...,575.950000,2617.290000,1061.120000,936.480000,667.910000,2124.450000,1182.000000,2027.350000,627.030000,4764.110000
7,2006-07,GDP (in Rs. Cr.),5139.910000,2102.260000,3124.380000,1947.100000,543.230000,1705.210000,5067.940000,441.480000,...,625.380000,2928.040000,1185.470000,1021.730000,760.570000,2154.260000,1381.720000,2251.720000,719.560000,5915.690000
8,2000-01,Growth Rate % (YoY),-1.375085,-10.846120,6.815101,-15.054052,-5.755356,-0.246921,1.903749,-8.442942,...,-8.938495,0.195145,-5.293251,0.826446,-2.914478,-0.045973,1.265190,-7.708555,-2.818697,-6.546192
9,2001-02,Growth Rate % (YoY),-9.556740,14.146380,4.171482,14.160145,13.285998,15.450745,7.304435,13.189984,...,5.789333,6.726109,3.010577,11.341525,12.966815,8.117243,4.139763,7.318969,10.966748,-12.475589
10,2002-03,Growth Rate % (YoY),17.275326,-6.506963,-4.491310,-12.072093,-0.513270,-2.400270,2.730231,-18.199013,...,-6.308589,-6.572917,-3.591441,-3.973492,-13.653545,2.520223,0.932554,-4.918055,-13.810185,15.415269
11,2003-04,Growth Rate % (YoY),18.936340,20.358748,15.703225,18.982747,16.501607,15.907972,9.140908,15.086626,...,9.630986,15.798177,10.955265,16.281723,13.653861,13.572035,15.054687,13.311235,11.418557,13.425541
12,2004-05,Growth Rate % (YoY),23.296262,8.445817,14.298072,2.505708,3.996707,12.866670,14.449676,1.776199,...,5.747192,8.402970,7.310825,1.390385,1.064218,9.283002,16.122479,11.318653,12.329276,14.716005
13,2005-06,Growth Rate % (YoY),-13.410305,5.921602,6.293355,11.716737,5.771083,8.046321,7.855417,10.754442,...,3.340929,4.159553,3.391763,10.517372,9.721880,7.615584,-11.631454,13.355400,9.069561,24.182109
14,2006-07,Growth Rate % (YoY),15.145996,12.801554,15.263554,12.530920,9.898847,9.966015,13.054768,14.042157,...,8.582342,11.872968,11.718750,9.103238,13.873127,1.403187,16.896785,11.067157,14.756870,24.171986

In [6]:
dfs[0].columns

Index(['Year', 'Description', ' Angul', 'Balangir', ' Balasore', 'Bargarh',
       'Baudh', 'Bhadrak', 'Cuttack', ' Deogarh', 'Dhenkanal', 'Gajapati',
       'Ganjam', ' Jagatsinghpur', ' Jajpur', 'Jharsuguda', 'Kalahandi',
       'Kandhamal', 'Kendrapara', 'Kendujhar', 'Khordha', 'Koraput',
       'Malkangiri', 'Mayurbhanj', ' Nabarangpur', ' Nayargarh', 'Nuapada',
       'Puri', 'Rayagada', 'Sambalpur', 'Sonapur', 'Sundargarh'],
      dtype='object')